//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VistasAct3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Categorias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categorias()
        {
            this.Subcategorias = new HashSet<Subcategorias>();
        }
    
        public int Id_categoria { get; set; }
        [Required(ErrorMessage ="Este campo es obligatorio")]
        [StringLength(50,ErrorMessage ="Máximo de 50 caracteres.")]
        [RegularExpression(@"^([A-Za-zÁáÉéÍíÓóÚú ]{2,50}$)",ErrorMessage ="Ingrese un nombre válido.")]
        public string nombre { get; set; }
        [Required(ErrorMessage ="Se necesita una descripción.")]
        [StringLength(80,ErrorMessage ="Máximo 80 caracteres.")]
        public string descripcion { get; set; }
        [Required(ErrorMessage ="El nombre de la imagen es requerido.")]
        [StringLength(80, ErrorMessage = "Máximo 80 caracteres.")]
        [RegularExpression(@"^([A-Za-z.]{2,50}$)", ErrorMessage = "No se permiten caracteres especiales.")]
        public string imagen { get; set; }
        [Required(ErrorMessage ="Es necesario seleccionar un estatus.")]
        public int estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subcategorias> Subcategorias { get; set; }
    }
}
