//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_Virtual_El_Chefcito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Envios()
        {
            this.Comentario = new HashSet<Comentario>();
        }
    
        public int id_envio { get; set; }
        public string contacto { get; set; }
        public string numero_guia { get; set; }
        public string direccion { get; set; }
        public int estatus { get; set; }
        public System.DateTime fecha_envio { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public int id_paqueteria { get; set; }
        public int id_detalle_venta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
        public virtual Detalle_Venta Detalle_Venta { get; set; }
        public virtual Paqueterias Paqueterias { get; set; }
    }
}
