//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_Virtual_El_Chefcito.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Comentario = new HashSet<Comentario>();
            this.Venta = new HashSet<Venta>();
        }

        public int id_usuario { get; set; }
        [Display(Name = "Nombre completo")]
        [Required(ErrorMessage = "Debe ser mayor o menor")]
        public string nombre { get; set; }
        [Display(Name = "Apellidos")]
        [Required(ErrorMessage = "Debe ser mayor o menor")]
        public string apellidos { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string rol { get; set; }
        public int estatus { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
