//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actividad3Vistas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas()
        {
            this.Comentario = new HashSet<Comentario>();
        }
    
        public int id_venta { get; set; }
        public System.DateTime fecha_venta { get; set; }
        public int cantidad { get; set; }
        public decimal precio_venta { get; set; }
        public int estatus { get; set; }
        public int id_producto { get; set; }
        public int id_usuario { get; set; }
        public int id_detalle_venta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Detalle_venta Detalle_venta { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
