//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_Virtual_El_Chefcito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int id_venta { get; set; }
        public Nullable<System.DateTime> fecha_venta { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_detalle_venta { get; set; }
    
        public virtual Detalle_Venta Detalle_Venta { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
